[project]
name = "tara"
revision = "1.0"
# Extend configurations from subdirectories
# extends = [ "subdir1", "subdir2" ]

[profiles.default]
MISTRAL_API_KEY = { description = "mistral api key" }

[profiles.development]
MISTRAL_API_KEY = { description = "mistral api key" }