[project]
name = "tara"
revision = "1.0"
# Extend configurations from subdirectories
# extends = [ "subdir1", "subdir2" ]

[profiles.default]
GOOGLE_API_KEY = { description = "google api key" }
GOOGLE_GENERATIVE_AI_API_KEY = { description = "google api key" }
POSTGRES_CONNECTION_STRING = { description = "postgres db connection string" }

[profiles.development]
GOOGLE_API_KEY = { description = "google api key" }
GOOGLE_GENERATIVE_AI_API_KEY = { description = "google api key" }
POSTGRES_CONNECTION_STRING = { description = "postgres db connection string" }